### ISSUE TITLE
Investigate Mongo and ObjectId()

### ISSUE THREAD

**Issue by jedrichards** [madebycomrades/autokitty#6]
Database documents created in the Mongo shell have `Object()` ids, whereas documents created from the site have string ids. What gives? What's the difference?

**Comment by m-allanson** [comment]
I've done a little reading and it seems that object `_ids` are the Mongo default.  In contrast to this, Meteor have chosen to implement `_ids` as strings because the client side implementation of mongo (minimongo) can not generate unique object `_ids` without a request to the server. 

As we're not working with existing Mongo data, it seems ok for autokitty to use Meteor's string `_id` convention.

Here's a brief pros and cons list of the types of `_ids`, largely taken from the links listed below.

### Object _id pros:
- it has an embedded timestamp in it. 
- it's the default Mongo `_id` type; ubiquitous, allowing interoperability with other apps and drivers.

### Object _id cons:
- it's an object, so a little more difficult to manipulate in practice. 
- object `_ids` have to be created server-side to maintain `_id` uniqueness, which makes client-side `_id` creation (by minimongo) problematic.

### String _id pros:
- reduced client side latency as `_ids` can be generated on the client.

### String _id cons:
- developer has to ensure uniqueness of `_ids`.
- Mongo `findAndModify()` and `getNextSequence()` queries may be invalidated.

### Other info

Meteor Collections have an `idGeneration` option that lets you specify whether to use string or object `_id` values.

More info at the following links:
- https://groups.google.com/forum/#!topic/meteor-talk/f-ljBdZOwPk
- http://stackoverflow.com/questions/15318184/meteor-collection-objectid-vs-mongodb-objectid
- http://stackoverflow.com/questions/23104825/why-is-the-id-for-a-mongo-document-string-but-not-objectid-by-default
- http://docs.mongodb.org/manual/reference/method/db.collection.findAndModify/
- http://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/

**Comment by jedrichards** [comment]
:+1:
